export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const ADD_NUMBER = 'ADD_NUMBER';
export const SUBSTRACT_NUMBER = 'SUBSTRACT_NUMBER';
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS ="FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE ="FETCH_USER_FAILURE";
